### PR TITLE
Add sand and soil feature

### PR DESCRIPTION
**Pull request by kelsey-taylor**
Starting by adding sand/soil to the default view, then setting up a separate view for sand/soil

### CODE REVIEW

**Comment by kelsey-taylor** [comment]
ok did some setup of the layers here — over to you @mwbernard

**Comment by mwbernard** [comment]
@kelsey-taylor Added UI for this and got the color palette working! Really like how its looking

**Comment by kelsey-taylor** [comment]
ooh yeah it's looking great @mwbernard! my two thoughts:
- can we remove the crop legend when in this mode? i think it's distracting and Cameron said it didn't matter much how legible the crop circles are in this view. i'd think a user understands by this point that green = more and orange = less
- can we disable the minimap in this view too? i'm finding it distracting / it might be sending the wrong message here...i could see it reading as "these are the good/bad areas for sand/soil" instead of relating just to the selected crop

**Comment by mwbernard** [comment]
@kelsey-taylor totally agree, doing that now

**Comment by kelsey-taylor** [comment]
nice! i think it's looking great 🌟 

the only tiny thing that occurs to me now is the kind of weird overlay for the headers — feels a lil distracting but honestly most people probably won't notice. i think it's fine to leave it as is unless someone else mentions it

Screenshot 2024-01-16 at 11 29 08 AM

**Pull request merged**
