### PR TITLE
Add cards and distribution plots

### LINKED ISSUE #11: Add beeswarm supplemental viz to app
Lets get a component going that brings in d3 and the data and shows the dots somewhere in a sidebar

### PR DESCRIPTION
**Pull request by mwbernard**
Closes #11 

This does a couple things. First off the swarm plots were causing some performance slowdown when crops are switched, so I've taken a stab at a replacement form, similar to some things we've talked about previously. Not 100% polished here, but generally I think showing a vertical distribution of lines conveys the same message as the swarms while being less distracting, and with some tweaks could look really nice. Here are some examples of the plots - I think effectively comparing scenarios, while also giving a good impression of how a crop compares to other crops (the y scale is consistent across all crops to aid this comparison):

sesame:
Screenshot 2023-11-19 at 2 57 30 PM

tomato:
Screenshot 2023-11-19 at 2 57 12 PM

maize:
Screenshot 2023-11-19 at 2 57 03 PM

I also included a first pass at a reusable card wrapper component that wraps around ^ these plots, and also around the crop cards in this view:

Screenshot 2023-11-19 at 3 05 15 PM

### CODE REVIEW

**Comment by kelsey-taylor** [comment]
@mwbernard i just finished these designs https://github.com/earthrise-media/vacs-map/issues/26 — do you want to include the crop card maps in this PR? i'm happy to wait a little so you have time to generate the static versions to add here

**Comment by mwbernard** [comment]
@kelsey-taylor hmm I think we can do that in a separate pr, I'm working on a script to generate the svg map images now

**Review by kelsey-taylor — COMMENTED** [review]
all the setup pieces look great and are working for me as expected!

as for the chart — it's showing up much more condensed on my screen, so much so that none of the crops get close to filling the container:

sesame:
Screenshot 2023-11-20 at 12 01 14 PM

tef:
Screenshot 2023-11-20 at 12 01 36 PM

It looks a bit different than the screenshots on your end, but I think the concept works if it's easy to see the variation between lines (as is the case in your screenshots). Is there something we can do there to make these more readable?

**Comment by mwbernard** [comment]
@kelsey-taylor good call! yeah need to make margins and line width smarter to account for this, gonna hold off merging for the moment.

**Comment by mwbernard** [comment]
@kelsey-taylor now these don't get screwed up at small window heights

Screenshot 2023-11-20 at 9 25 12 AM

**Review by kelsey-taylor — APPROVED** [review]
looking great now! i have a feeling they might come back and ask for some kind of legend/tooltip later but honestly i like these more than the beeswarms on their own 🐝

**Pull request merged**
