### PR TITLE
Add dot hover for grid overlay

### LINKED ISSUE #29: Add map dot hover
For now lets add a `hovered` feature state and show hover with a stroke

### PR DESCRIPTION
**Pull request by mwbernard**
Closes #29 

This adds basic hover to the grid overlay elements, updating their feature states and also tracking the hovered grid id for use throughout the app. It also registers the hovered elements in the distribution plot and shows them graphically. The styling is not what we'll want, but I'm going to leave that for the distribution plot update that's on its way.

@kelsey-taylor not sure what you had in mind for the hovered styling on the map, so I kept this pretty basic for now, just turning down opacity on hover to make sure it was working. I was also wondering if we'd like the hovered element to be the entire grid cell rather than just the dot we're showing - that way there would more consistently be a hovered element when moving the mouse over the dots. I feel like there are a a bunch of options for how to do that but lmk if you agree or not!

### CODE REVIEW

**Review by kelsey-taylor — COMMENTED** [review]
looking good so far! 

i think i'd like to see the stroke outline for the grid dots be white on hover to match the chart, but i also like the idea of using the entire grid cell. we don't really surface anywhere else that these points represent areas, but i think that'd help a lot with the interaction here while subtly showing the grid cell

**Comment by mwbernard** [comment]
Small conflict between this and #59 - so don't want to touch the distribution plots here anymore. I think lets settle on a map interaction for now, and then leave the distribution plot effects for #59 to clean up.

**Comment by mwbernard** [comment]
@ebrelsford wondering if you have thoughts on the question above ^ about hovering over a dot itself vs. hovering over a grid cell, and how we might best implement that?

**Comment by ebrelsford** [comment]
We'd have to create a file of the actual grid cells, right now we just have the center points of them. That file is relatively large so ideally we would assign the same ids to the grid cells and upload the file as a tileset to their Mapbox account, then add the tileset as a layer that's hidden by default.

**Review by kelsey-taylor — APPROVED** [review]
this looks good!

**Pull request merged**
